FROM golang:1.22.5-alpine AS build
WORKDIR /src
RUN apk add --no-cache git
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -buildvcs=false -o /out/api ./cmd/api

FROM alpine:3.20
RUN apk add --no-cache ca-certificates curl
WORKDIR /app
COPY --from=build /out/api /app/api
COPY migrations /app/migrations
COPY docs /app/docs
EXPOSE 8080
CMD ["/app/api"]
