CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  display_name VARCHAR(100) NOT NULL,
  phone VARCHAR(50) DEFAULT '',
  email VARCHAR(150) DEFAULT '',
  status VARCHAR(32) NOT NULL,
  last_login_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL
);

CREATE TABLE IF NOT EXISTS roles (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(100) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(255) DEFAULT '',
  built_in TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL
);

CREATE TABLE IF NOT EXISTS permissions (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(100) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  module VARCHAR(100) NOT NULL,
  description VARCHAR(255) DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL
);

CREATE TABLE IF NOT EXISTS user_roles (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS role_permissions (
  role_id BIGINT NOT NULL,
  permission_id BIGINT NOT NULL,
  PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS customers (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(200) NOT NULL,
  contact_name VARCHAR(100) DEFAULT '',
  contact_phone VARCHAR(100) DEFAULT '',
  address VARCHAR(255) DEFAULT '',
  region VARCHAR(100) DEFAULT '',
  level VARCHAR(32) DEFAULT 'normal',
  contract_number VARCHAR(100) DEFAULT '',
  service_weekdays VARCHAR(50) DEFAULT '',
  service_month_days VARCHAR(100) DEFAULT '',
  temporary_allowed TINYINT(1) NOT NULL DEFAULT 0,
  service_windows VARCHAR(255) DEFAULT '',
  status VARCHAR(32) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL
);

CREATE TABLE IF NOT EXISTS waste_categories (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(100) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(255) DEFAULT '',
  default_rate DECIMAL(12,2) NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL
);

CREATE TABLE IF NOT EXISTS containers (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  customer_id BIGINT NOT NULL,
  type VARCHAR(50) NOT NULL,
  number VARCHAR(100) NOT NULL,
  capacity_l INT NOT NULL,
  quantity INT NOT NULL,
  longitude DECIMAL(12,6) DEFAULT 0,
  latitude DECIMAL(12,6) DEFAULT 0,
  location VARCHAR(255) DEFAULT '',
  status VARCHAR(32) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL
);

CREATE TABLE IF NOT EXISTS vehicles (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  plate_number VARCHAR(32) NOT NULL UNIQUE,
  model VARCHAR(100) DEFAULT '',
  rated_load_tons DECIMAL(12,2) NOT NULL DEFAULT 0,
  current_mileage_km DECIMAL(12,2) NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL,
  inspection_due_date DATE NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL
);

CREATE TABLE IF NOT EXISTS drivers (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  phone VARCHAR(50) DEFAULT '',
  license_number VARCHAR(100) DEFAULT '',
  license_class VARCHAR(50) DEFAULT '',
  hire_date DATE NULL,
  status VARCHAR(32) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL
);

CREATE TABLE IF NOT EXISTS collection_plans (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(200) NOT NULL,
  customer_id BIGINT NOT NULL,
  version INT NOT NULL DEFAULT 1,
  status VARCHAR(32) NOT NULL,
  holiday_strategy VARCHAR(32) DEFAULT '',
  effective_from DATE NULL,
  effective_to DATE NULL,
  estimated_weight_tons DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL
);

CREATE TABLE IF NOT EXISTS plan_rules (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  plan_id BIGINT NOT NULL,
  rule_type VARCHAR(32) NOT NULL,
  rule_value VARCHAR(255) NOT NULL,
  start_time VARCHAR(32) DEFAULT '',
  end_time VARCHAR(32) DEFAULT '',
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL
);

CREATE TABLE IF NOT EXISTS routes (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(200) NOT NULL,
  plan_id BIGINT NOT NULL,
  vehicle_id BIGINT NOT NULL,
  driver_id BIGINT NOT NULL,
  status VARCHAR(32) NOT NULL,
  estimated_weight_tons DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL
);

CREATE TABLE IF NOT EXISTS route_stops (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  route_id BIGINT NOT NULL,
  customer_id BIGINT NOT NULL,
  sequence_no INT NOT NULL,
  estimated_arrival VARCHAR(32) DEFAULT '',
  stay_minutes INT NOT NULL DEFAULT 0,
  estimated_weight_tons DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL
);

CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  task_number VARCHAR(100) NOT NULL UNIQUE,
  plan_id BIGINT NOT NULL,
  route_id BIGINT NULL,
  driver_id BIGINT NULL,
  plan_date DATE NOT NULL,
  status VARCHAR(32) NOT NULL,
  claimed_at DATETIME NULL,
  completed_at DATETIME NULL,
  mileage_km DECIMAL(12,2) NOT NULL DEFAULT 0,
  fuel_liters DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL
);

CREATE TABLE IF NOT EXISTS task_stops (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  task_id BIGINT NOT NULL,
  customer_id BIGINT NOT NULL,
  sequence_no INT NOT NULL,
  status VARCHAR(32) NOT NULL,
  arrived_at DATETIME NULL,
  completed_at DATETIME NULL,
  longitude DECIMAL(12,6) DEFAULT 0,
  latitude DECIMAL(12,6) DEFAULT 0,
  actual_weight_tons DECIMAL(12,2) NOT NULL DEFAULT 0,
  skip_reason VARCHAR(100) DEFAULT '',
  notes VARCHAR(255) DEFAULT '',
  photos TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL
);

CREATE TABLE IF NOT EXISTS weighing_records (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  task_id BIGINT NOT NULL,
  customer_id BIGINT NOT NULL,
  vehicle_id BIGINT NOT NULL,
  scale_id BIGINT NOT NULL,
  gross_weight DECIMAL(12,2) NOT NULL DEFAULT 0,
  tare_weight DECIMAL(12,2) NOT NULL DEFAULT 0,
  net_weight DECIMAL(12,2) NOT NULL DEFAULT 0,
  weigh_time DATETIME NOT NULL,
  is_manual TINYINT(1) NOT NULL DEFAULT 0,
  manual_reason VARCHAR(255) DEFAULT '',
  status VARCHAR(32) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL
);

CREATE TABLE IF NOT EXISTS weighing_histories (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  weighing_record_id BIGINT NOT NULL,
  original_gross DECIMAL(12,2) NOT NULL DEFAULT 0,
  original_tare DECIMAL(12,2) NOT NULL DEFAULT 0,
  corrected_gross DECIMAL(12,2) NOT NULL DEFAULT 0,
  corrected_tare DECIMAL(12,2) NOT NULL DEFAULT 0,
  reason VARCHAR(255) DEFAULT '',
  operator_id BIGINT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS weighing_abnormalities (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  weighing_record_id BIGINT NOT NULL,
  type VARCHAR(100) NOT NULL,
  description VARCHAR(255) DEFAULT '',
  status VARCHAR(32) NOT NULL,
  reviewer_id BIGINT NULL,
  reviewed_at DATETIME NULL,
  review_result VARCHAR(32) DEFAULT '',
  reject_reason VARCHAR(255) DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS invoices (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  invoice_number VARCHAR(100) NOT NULL UNIQUE,
  customer_id BIGINT NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  billing_mode VARCHAR(50) NOT NULL,
  subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
  surcharge DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  paid_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL,
  due_date DATE NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL
);

CREATE TABLE IF NOT EXISTS invoice_items (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  invoice_id BIGINT NOT NULL,
  task_id BIGINT NOT NULL,
  service_date DATE NOT NULL,
  waste_category_id BIGINT NOT NULL,
  net_weight DECIMAL(12,2) NOT NULL DEFAULT 0,
  item_type VARCHAR(50) NOT NULL,
  description VARCHAR(255) DEFAULT '',
  unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  quantity DECIMAL(12,2) NOT NULL DEFAULT 0,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL
);

CREATE TABLE IF NOT EXISTS payment_records (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  invoice_id BIGINT NOT NULL,
  payment_time DATETIME NOT NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  operator_id BIGINT NOT NULL,
  payment_method VARCHAR(50) NOT NULL,
  voucher_number VARCHAR(100) DEFAULT '',
  notes VARCHAR(255) DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NULL,
  username VARCHAR(100) DEFAULT '',
  action VARCHAR(100) NOT NULL,
  resource_type VARCHAR(100) NOT NULL,
  resource_id VARCHAR(100) DEFAULT '',
  before_value TEXT NULL,
  after_value TEXT NULL,
  ip_address VARCHAR(100) DEFAULT '',
  user_agent VARCHAR(255) DEFAULT '',
  request_id VARCHAR(100) DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS holiday_config (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  holiday_date DATE NOT NULL,
  name VARCHAR(100) NOT NULL,
  is_workday TINYINT(1) NOT NULL DEFAULT 0,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL
);

CREATE TABLE IF NOT EXISTS system_configs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  config_key VARCHAR(100) NOT NULL UNIQUE,
  config_value TEXT NOT NULL,
  value_type VARCHAR(50) NOT NULL,
  module VARCHAR(100) DEFAULT '',
  description VARCHAR(255) DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL
);
